---@class v1.ProjectOptions
---
--- Manual mode doesn't automatically change your root directory, so you have the option to manually do so using
--- `:ProjectRoot` command.
---@field manual_mode? boolean
---
--- Methods of detecting the root directory. Here order matters: if one is not detected, the other is used as fallback.
--- You can also delete or rearrange the detection methods.
---@field detection_methods? v1.DetectionMethod[]
---
--- All the patterns used to detect root dir, when `"pattern"` is in `detection_methods`.
---@field patterns? string[]
---
--- Table of lsp clients to ignore by name.
--- For example: `{ "efm", ... }`
---@field ignore_lsp? string[]
---
--- Don't calculate root dir on specific directories.
--- For example: `{ "~/.cargo/*", ... }`
---@field exclude_dirs? string[]
---
--- Show hidden files in telescope.
---@field show_hidden? boolean
---
--- When set to false, you will get a message when project.nvim changes your directory.
---@field silent_chdir? boolean
---
--- What scope to change the directory.
---@field scope_chdir? v1.ChdirScope
---
--- Path where project.nvim will store the project history for use in telescope.
---@field datapath? string

---@alias v1.DetectionMethod
---| "lsp" uses the native neovim lsp
---| "pattern" uses vim-rooter like glob pattern matching.

---@alias v1.ChdirScope
---| "global" (default)
---| "tab"
---| "win"
