-- TODO: Define types.
--
---@class projects.UserConfig
---
---@class projects.AddProjectOpts
---@class projects.DeleteProjectOpts
---@class projects.GetRecentProjectsOpts
---@class projects.EnterProjectDirectoryOpts
---
---@class projects.State
