---
name: ci
on:  # yamllint disable-line rule:truthy
  pull_request:
    branches: [main]
  push:
    branches: [main]
jobs:
  checks:
    name: checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: StyLua
        uses: JohnnyMorganz/stylua-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
          args: --check .
      - name: Luacheck
        uses: lunarmodules/luacheck@v1.2.0
